---
version: 0.2
phases:
  install:
    commands:
      - apt-get update -y 
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - curl -sS -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      - unzip -qq awscliv2.zip
      - ./aws/install  
      - export PATH=$PWD/:$PATH
      

  pre_build:
    commands:
      - export KUBECONFIG=$HOME/.kube/config
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $EKS_CLUSTER_REGION
  
  build:
    commands:
      - CURRENT_INGRESS=$(kubectl get ingress ingress-alb -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
      - kubectl apply -f ./microservices/release/kubernetes-manifests-$AWS_REGION.yaml
      - INGRESS=$(kubectl get ingress ingress-alb -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')


  post_build:
    commands:
      - |
        if [ "$CURRENT_INGRESS" = "$INGRESS" ]; then
          echo "All Records Up to date"
        elif [ $AWS_REGION = "ap-southeast-1" ]; then
          echo "Entering apse1"
          ENDPOINT_GROUP_ARN=arn:aws:globalaccelerator::$ACCOUNT_ID:accelerator/a6c379cd-ae5b-4723-810b-ccd4215dc560/listener/9e92e0e9/endpoint-group/7d7b4aa69c00
          aws globalaccelerator update-endpoint-group --region us-west-2 --endpoint-group-arn $ENDPOINT_GROUP_ARN --endpoint-configurations EndpointId=$(aws elbv2 describe-load-balancers --region $AWS_REGION --query "LoadBalancers[?contains(DNSName, '$Ingress')].LoadBalancerArn" --output text),Weight=128,ClientIPPreservationEnabled=True 
        else
          echo "Entering apse2"
          ENDPOINT_GROUP_ARN=arn:aws:globalaccelerator::$ACCOUNT_ID:accelerator/a6c379cd-ae5b-4723-810b-ccd4215dc560/listener/9e92e0e9/endpoint-group/7a660b94b00c
          aws globalaccelerator update-endpoint-group --region us-west-2 --endpoint-group-arn $ENDPOINT_GROUP_ARN --endpoint-configurations EndpointId=$(aws elbv2 describe-load-balancers --region $AWS_REGION --query "LoadBalancers[?contains(DNSName, '$Ingress')].LoadBalancerArn" --output text),Weight=128,ClientIPPreservationEnabled=True  
        fi